name: Deploy to AWS EC2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/aws_key.pem
        chmod 600 ~/.ssh/aws_key.pem
        ssh-keyscan -H 3.134.91.37 >> ~/.ssh/known_hosts

    - name: Copy project files to EC2
      run: |
        scp -i ~/.ssh/aws_key.pem -r spring-boot-app ubuntu@3.134.91.37:~/app/
        scp -i ~/.ssh/aws_key.pem Dockerfile ubuntu@3.134.91.37:~/app/
        scp -i ~/.ssh/aws_key.pem docker-compose.yml ubuntu@3.134.91.37:~/app/

    - name: Deploy application with Docker Compose
      run: |
        ssh -i ~/.ssh/aws_key.pem ubuntu@3.134.91.37 << 'EOF'
          cd ~/app
          sudo docker compose down || true
          sudo docker compose up --build -d
        EOF
